Repository devSquad-study/2023-CS-Study, pull requests merged in 2023-02, with the labels that each got.

#37 [은선] 메모리 계층(Memory Hierarchy)
  OS/img/os_memory_cache.png
  OS/img/os_memory_cache_3.png
  OS/img/os_memory_cache_hit_miss.png
  OS/img/os_memory_decode1.png
  OS/img/os_memory_decode2.png
  OS/img/os_memory_example.png
  OS/img/os_memory_hierarchy.png
  OS/os_memory_hierarchy.md
Labels: 운영체제

#40 [주디] 동기화(스핀락, 뮤텍스, 세마포어)
  OS/img/os_synchronization_critical_section.png
  OS/img/os_synchronization_data_access.png
  OS/img/os_synchronization_race_condition.png
  OS/img/os_synchronization_race_condition1.png
  OS/img/os_synchronization_race_condition2.png
  OS/img/os_synchronization_race_condition3.png
  OS/os_deadLock.md
  OS/os_process_synchronization.md
Labels: 운영체제

#38 [네오] TLB
  OS/img/os_tlb_1.svg
  OS/img/os_tlb_2.svg
  OS/os_tlb.md
Labels: 운영체제

#39 [수연] PCB & Context Switching
  OS/img/os_context_switching.png
  OS/img/os_pcd_structure.png
  OS/img/os_process_state.jpg
  OS/os_pcd_and_context_switching.md
Labels: 운영체제

#36 [상혁] 시스템 콜
  OS/img/os_library_function.jpg
  OS/img/os_modebit.PNG
  OS/img/os_operating_system_structure.png
  OS/img/os_printf_process.png
  OS/img/os_system_call_command.png
  OS/img/os_system_call_process.png
  OS/img/os_system_call_process2.png
  OS/os_system_call.md
Labels: 운영체제

#41 [hash] 멀티프로세스, 스레드와 멀티스레딩
  OS/Export-672b4efd-0678-454b-87e9-8e01a4df9370/os_multi_procsss_thread_multi_thread.md
  OS/Export-672b4efd-0678-454b-87e9-8e01a4df9370/멀티프로세스, 스레드와 멀티스레딩/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-02-02_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_6.26.40.png
  OS/운영체제와 컴퓨터.md
  OS/운영체제와 컴퓨터/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-01-24_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_2.35.46.png
Labels: 운영체제

#47 [주디] 동기화(스핀락, 뮤텍스, 세마포어) 예시 추가
  OS/README.md
  OS/os_process_synchronization.md
  README.md
Labels: operating system

#49 [팬시] TLB (Advanced Version)
  OS/img/os-tlb-1.png
  OS/img/os-tlb-2.png
  OS/img/os-tlb-3.png
  OS/img/os-tlb-cache.png
  OS/img/os-tlb-context-switching-to-solve-problem-2.png
  OS/img/os-tlb-context-switching-to-solve-problem.png
  OS/img/os-tlb-ex-accessing-an-array.png
  OS/img/os-tlb-issue-1.png
  OS/img/os-tlb-issue-2.png
  OS/img/os-tlb-issue-3.png
  OS/img/os-tlb-locality-1.png
  OS/img/os-tlb-locality-2.png
  OS/img/os-tlb-replacement-policy-LRU.png .png
  OS/os_tlb_advanced.md
Labels: operating system

#55 [팬시] README.md 수정
  README.md
Labels: README.md

#57 [주디] README.md 내용 수정
  README.md
Labels: README.md

#59 [팬시] Paging: Smaller Table
  OS/img/os-paging-smaller-tables-1.png
  OS/img/os-paging-smaller-tables-2.png
  OS/img/os-paging-smaller-tables-3.png
  OS/img/os-paging-smaller-tables-4.png
  OS/img/os-paging-smaller-tables-5.png
  OS/img/os-paging-smaller-tables-6.png
  OS/img/os-paging-smaller-tables-7.png
  OS/img/os-paging-smaller-tables-8.png
  OS/os_paging_smaller_table.md
Labels: operating system

#63 [은선] RDB와 NoSQL에서의 클러스터링/레플리케이션 방식
  DB/db_rdb_nosql_replication_and_clustering.md
  DB/img/db_clustering_activ_active.png
  DB/img/db_clustering_activ_standby.png
  DB/img/db_database_structure.png
  DB/img/db_dynamic_sharding.png
  DB/img/db_entity_group_sharding.png
  DB/img/db_hash_sharding.png
  DB/img/db_mongodb_cluster.png
  DB/img/db_mongodb_cluster_2.png
  DB/img/db_mongodb_replication.png
  DB/img/db_mongodb_replication_2.png
  DB/img/db_mongodb_replication_3.png
  DB/img/db_mysql_clustering.png
  DB/img/db_mysql_clustering_2.png
  DB/img/db_mysql_replication.png
  DB/img/db_replication.png
  DB/img/db_sharding.png
  OS/os_memory_hierarchy.md
Labels: database

#62 [상혁] ERD와 정규화 과정
  DB/db_erd_normalization.md
  DB/img/db_1NF_1.png
  DB/img/db_1NF_2.png
  DB/img/db_1NF_violation.png
  DB/img/db_2NF_1.png
  DB/img/db_2NF_2.png
  DB/img/db_2NF_violation.png
  DB/img/db_3NF.png
  DB/img/db_3NF_violation.png
  DB/img/db_erd_notation.jpg
  DB/img/db_erd_relationship_participation.png
  DB/img/db_identifying_relationship.png
  DB/img/db_many_to_many_cardinality.png
  DB/img/db_many_to_many_middle.png
  DB/img/db_non_identifying_relationship.png
  DB/img/db_normalization.png
  DB/img/db_one_to_many_cardinality.png
  DB/img/db_one_to_one_cardinality.png
  DB/img/db_student_entity.png
  DB/img/db_student_entity_attribute.png
  DB/img/db_student_entity_domain.png
  DB/img/db_student_entity_example.png
Labels: database

#61 [네오] 데이터베이스 키
  DB/db_key.md
  DB/img/db_key_1.png
Labels: database

#60 [주디] 트랜잭션 (개념, ACID, concurrency control, Isolation level)
  DB/db_transaction_and_acid.md
  DB/db_transaction_concurrency-control.md
  DB/db_transaction_isolation_level.md
  DB/img/cascadeless_schedule_ex1.png
  DB/img/conflict_equivalent_ex1.png
  DB/img/conflict_ex1.png
  DB/img/dirty_read.png
  DB/img/isolation_example.png
  DB/img/isolation_level.png
  DB/img/non-repeatable_read.png
  DB/img/recoverable_schedule.png
  DB/img/recoverable_schedule_ex1.png
  DB/img/transaction_java.png
  DB/img/transaction_status.png
  DB/img/unrecoverable_schedule_ex1.png
  Network/network_dns_and_network_flow.md
Labels: database

#64 [현철] B-tree와 B+tree
  DB/README.md
  DB/db_b_tree_b+tree.md
  DB/img/db_b_tree_b+tree_1.png
  DB/img/db_b_tree_b+tree_10.png
  DB/img/db_b_tree_b+tree_11.png
  DB/img/db_b_tree_b+tree_12.png
  DB/img/db_b_tree_b+tree_13.png
  DB/img/db_b_tree_b+tree_2.png
  DB/img/db_b_tree_b+tree_3.png
  DB/img/db_b_tree_b+tree_4.png
  DB/img/db_b_tree_b+tree_5.png
  DB/img/db_b_tree_b+tree_6.png
  DB/img/db_b_tree_b+tree_7.png
  DB/img/db_b_tree_b+tree_8.png
  DB/img/db_b_tree_b+tree_9.png
Labels: database

#66 chore : db_b_tree_b+tree "파일 확장자 변경"
  DB/db_b_tree_b+tree.md
Labels: database

#67 [팬시] RDB와 NoSQL " 오타 수정 "
  DB/db_rdb_and_nosql.md
Labels: database, modify contents

#69 [주디] README.md 수정
  DB/README.md
  README.md
Labels: README.md

#70 [팬시] RDB와 NoSQL " 전반적인 내용 검토 및 수정 "
  DB/db_rdb_and_nosql.md
Labels: database, modify contents

#71 [은선] 메모리 계층 "오타 수정"
  OS/os_memory_hierarchy.md
Labels: operating system, modify contents

#73 [은선] 저장 프로시저(stored procedure)
  DB/db_stored_procedure.md
  DB/img/db_sp_01.png
  DB/img/db_sp_02.png
  DB/img/db_sp_03.png
  DB/img/db_sp_04.png
  DB/img/db_sp_05.png
Labels: database

#74 chore: [Network] network_cookie_and_session.md 내용 수정
  Network/network_cookie_and_session.md
Labels: modify contents

#76 [네오] DB Join
  DB/db_join.md
  DB/img/db_join01.png
  DB/img/db_join02.png
  DB/img/db_join03.png
  DB/img/db_join04.png
  DB/img/db_join05.png
  DB/img/db_join06.png
  DB/img/db_join07.png
Labels: database

#72 [주디] DB 인덱스(Index)
  DB/README.md
  DB/db_index.md
  DB/db_transaction_and_acid.md
  DB/db_transaction_concurrency-control.md
  DB/db_transaction_isolation_level.md
  DB/img/b+tree.png
  DB/img/db_index.png
  DB/img/full_scan.png
  DB/img/hash_table.png
  DB/img/multi_level_indexes.png
  DB/img/secondary_storage.png
  DB/img/single_index.png
  Network/network_dns_and_network_flow.md
  Network/network_http.md
  OS/os_deadLock.md
  OS/os_process_synchronization.md
Labels: database

#77 [현철] DB redis
  DB/db_redis.md
Labels: database

#80 [수연] DB Trigger
  DB/db_trigger.md
  DB/img/db_trigger_table1.PNG
  DB/img/db_trigger_table2.PNG
  DB/img/db_trigger_table3.PNG
  DB/img/db_trigger_table4.PNG
Labels: database

#75 [팬시] DB locking
  DB/db_locking.md
  DB/img/db-locking-1.png
  DB/img/db-locking-2.png
  DB/img/db-locking-3.png
  DB/img/db-locking-4.png
  DB/img/db-locking-deadlock.png
  DB/img/db-locking-optimistic-lock.png
  DB/img/db-locking-pessimistic-lock.png
Labels: database

#81 [팬시] [DB] README.md 목차 업데이트
  DB/README.md
Labels: README.md

#83 [주디] DB index 내용 추가
  DB/db_index.md
  DB/img/index_breakeven_point.png
  DB/img/random_access.jpeg
  README.md
Labels: database, modify contents

#88 [팬시] The Abstractoin: Address Space
  OS/img/os-13-address-space-1.png
  OS/img/os-13-address-space-2.png
  OS/img/os-13-address-space-3.png
  OS/img/os-13-address-space-4.png
  OS/os_address_space.md
Labels: operating system

#87 Refactor : [팬시] Address Translation
  OS/img/os-15-address-translation-1.png
  OS/img/os-15-address-translation-2.png
  OS/img/os-15-address-translation-3.png
  OS/img/os-15-address-translation-4.png
  OS/img/os-15-address-translation-5.png
  OS/img/os-15-address-translation-6.png
  OS/img/os-15-address-translation-7.png
  OS/os_address_traslation.md
Labels: operating system, modify contents
